package com.quantback.strategy;

/**
 * Represents a decision generated by a trading strategy.
 * A Signal is not an order; it expresses intent (BUY, SELL, HOLD)
 * which an OrderManager later translates into executable orders.
 */
public enum Signal {
    BUY,
    SELL,
    HOLD
}
